# Generated by Django 5.1.5 on 2025-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_formdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
