# Generated by Django 5.1.5 on 2025-05-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_formdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
